HOSTNAME = '127.0.0.1'
PORT = '3306'
DATABASE = 'flask1'
USERNAME = 'root'
PASSWORD = '123456'
DB_URI = 'mysql+pymysql://{}:{}@{}:{}/{}'.format(USERNAME, PASSWORD, HOSTNAME, PORT, DATABASE)
SQLALCHEMY_TRACK_MODIFICATIONS = False
JSON_AS_ASCII = False
SQLALCHEMY_DATABASE_URI = DB_URI
SECRET_KEY='uwILLNO'

# 邮箱配置
MAIL_SERVER = "smtp.qq.com"
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_DEBUG = True
MAIL_USERNAME = "44910244@qq.com"
MAIL_PASSWORD = "ekkpvlvymbzybjcf"
DEFAULT_MAIL_SENDER = "44910244@qq.com"